version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p@assword
      POSTGRES_DB: cryptodata
    ports:
      - "5432:5432"  # Map PostgreSQL default port
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
